In [1]:
import torch
print(torch.__version__)

2.5.1


In [ ]:
# this will return false in apple silicon devices, as CUDA is explicitly for NVIDA GPUs
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")

GPU is not available. Using CPU


In [3]:
# For modern apple silicon chips
if torch.backends.mps.is_available():
    device = torch.device("mps") # we will need this device to force tensors to use mps
    print("Using apple silicon GPU acceleration (MPS)")
else:
    device = torch.device("cpu")
    print("MPS device not found. Using CPU")

Using apple silicon GPU acceleration (MPS)


We can use the `device` [whether it is GPU or CPU] by using this convention:
```bash
torch.rand((2, 3), device=device) # this will point to which device we are intending to use
```

### Moving an existing tensor to GPU from CPU

```bash
a = torch.rand(2, 3)

b = a.to(device)
```


# Creating a Tensor

In [ ]:
# using empty
## it creates empty tensor, (2, 3) is the shape. 
## empty function allocates memory for us, as the given shape (dimension)
## it will not necessarily have all 0s, it will allocate the existing values
## of the allocated space
a = torch.empty(2, 3) 

In [8]:
# using type
type(a)

torch.Tensor

In [9]:
# using zeros
## it will give a tensor with all 0 values of a given shape
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
# using rand
torch.rand(2, 3)

tensor([[0.0580, 0.4132, 0.0371],
        [0.0515, 0.4960, 0.6580]])

In [6]:
# using seed
## this will retain the random tensor over the same ipynb file, for a same seed number, in this case the number is 100
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# verifying the seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# for creating custom tensors
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways
# arange -> creates tensors of a range, torch.arange(start, end, diff)
torch.arange(0, 10, 2)

# using linspace -> evenly spaced values: torch.linspace(start, end, even_space_between_each)
torch.linspace(0, 10, 10)

# usingb eye -> eye for identity matrix, size should be given to the parameter
torch.eye(5)

# torch.full -> fill up a full matrix with a same value
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [16]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape # dimension of the tensor

torch.Size([2, 3])

In [18]:
# Make an empty tensor of same shape as x
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
# same for zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Mathematical Operations

### Scaler Operations

In [24]:
x = torch.rand(2, 2)
x

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [27]:
# addition
print(f"Add 2 to each cell: {x + 2}")

# subtraction
print(f"Subtract 2 from each cell: {x - 2}")


# multiplication
print(f"Multiply 2 with each cell: {x * 2}")

# division
print(f"Divide 2 from each cell: {x / 2}")

# int division
print(f"Integer division: {(x * 100) // 3}")

# mod
print(f"Mod 2: {((x * 100) // 3) % 2}")

# power
print(f"Square: {x**2}")


Add 2 to each cell: tensor([[2.1217, 2.7356],
        [2.7118, 2.7876]])
Subtract 2 from each cell: tensor([[-1.8783, -1.2644],
        [-1.2882, -1.2124]])
Multiply 2 with each cell: tensor([[0.2434, 1.4712],
        [1.4235, 1.5752]])
Divide 2 from each cell: tensor([[0.0608, 0.3678],
        [0.3559, 0.3938]])
Integer division: tensor([[ 4., 24.],
        [23., 26.]])
Mod 2: tensor([[0., 0.],
        [1., 0.]])
Square: tensor([[0.0148, 0.5411],
        [0.5066, 0.6203]])


### Element wise operation

In [28]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.4183, 0.9014, 0.9969],
        [0.7565, 0.2239, 0.3023]])
tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])


In [29]:
# add
print(f"Adding two tensors: {a + b}")

# sub
print(f"Subtracting: {a - b}")

# multiplication
print(f"Multiplication: {a * b}")

# division
print(f"Division: {a / b}")

# power
print(f"Power: {a**b}")

# mod
print(f"Mod: {a % b}")


Adding two tensors: tensor([[0.5967, 1.7253, 1.5526],
        [1.7335, 0.6679, 1.2502]])
Subtracting: tensor([[ 0.2399,  0.0776,  0.4411],
        [-0.2205, -0.2201, -0.6455]])
Multiplication: tensor([[0.0746, 0.7426, 0.5540],
        [0.7391, 0.0994, 0.2866]])
Division: tensor([[2.3445, 1.0942, 1.7938],
        [0.7743, 0.5042, 0.3190]])
Power: tensor([[0.8560, 0.9180, 0.9983],
        [0.7614, 0.5145, 0.3218]])
Mod: tensor([[0.0615, 0.0776, 0.4411],
        [0.7565, 0.2239, 0.3023]])


In [30]:
c = torch.tensor([2, 3, 4, 5])

# to make tensor in a certain range (min, max). The elements greater than max will become max, the elements less than min will become min
torch.clamp(c, min=3, max=4)

tensor([3, 3, 4, 4])

### Reduction Operation

In [38]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 9., 5.],
        [7., 3., 9.]])

In [39]:
# sum of all of the elements of tensor e
print(f"Sum of all the elements: {torch.sum(e)}")

# sum along columns
print(f"Sum of each column: {torch.sum(e, dim=0)}") # dim 0 will make a tensor of 1 dimension of each columns sum

# sum along rows
print(f"Sum along each row: {torch.sum(e, dim=1)}")


Sum of all the elements: 33.0
Sum of each column: tensor([ 7., 12., 14.])
Sum along each row: tensor([14., 19.])


In [40]:
# mean -> only works when datatype is either a floating point or complex dtype
print(f"Mean of all elements: {torch.mean(e)}")

# mean along col
print(f"Mean of each column: {torch.mean(e, dim=0)}")

# mean along row
print(f"Mean of each row: {torch.mean(e, dim=1)}")

Mean of all elements: 5.5
Mean of each column: tensor([3.5000, 6.0000, 7.0000])
Mean of each row: tensor([4.6667, 6.3333])


In [41]:
# median
torch.median(e)

tensor(5.)

In [42]:
# argmax -> gets the index/position of the maximum item
torch.argmax(e)

tensor(1)

### Matrix Operation

In [44]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [45]:
torch.matmul(f, g)

tensor([[120,  40],
        [125,  60]])

In [46]:
# dot product
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

torch.dot(v1, v2)

tensor(11)

In [48]:
# transpose
print(f"Swap columns with row: {torch.transpose(f, 0, 1)}") # 0, 1 means swap column with row

Swap columns with row: tensor([[7, 6],
        [9, 7],
        [2, 7]])


### Comparison Operations

In [49]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[0, 4, 3],
        [8, 8, 3]])
tensor([[3, 5, 0],
        [6, 4, 0]])


In [51]:
# greater than
print(f"greater than operation: {i > j}")

# less than
print(f"less than operation: {i < j}")

# equal to
print(f"equal to operation: {i == j}")

# not equal to
print(f"Not Equal to operation: {i != j}")

greater than operation: tensor([[False, False,  True],
        [ True,  True,  True]])
less than operation: tensor([[ True,  True, False],
        [False, False, False]])
equal to operation: tensor([[False, False, False],
        [False, False, False]])
Not Equal to operation: tensor([[True, True, True],
        [True, True, True]])


### Inplace operations

In [2]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.2647, 0.7680, 0.9655],
        [0.9995, 0.0605, 0.8927]])
tensor([[0.8897, 0.6245, 0.3864],
        [0.4376, 0.4295, 0.6413]])


In [4]:
m + n # this is being stored in a new tensor

tensor([[1.1544, 1.3924, 1.3519],
        [1.4371, 0.4900, 1.5340]])

In [5]:
m.add_(n) # this will store m + n into m's place

tensor([[1.1544, 1.3924, 1.3519],
        [1.4371, 0.4900, 1.5340]])

In [7]:
m.relu_() # this will store m's value after applying relu in m again

tensor([[1.1544, 1.3924, 1.3519],
        [1.4371, 0.4900, 1.5340]])

The trailing underscore after the functions add, relu will make it an inplace operation

### Copying a tensor

Assignment operator `=` makes copies the reference, not the value. Let's say, a is a tensor, we made another tensor b = a. Now if we make any changes into a, the same change will be applied to b as well. 
For avoiding this, we have to use `clone()` method. if we do
```bash
b = a.clone()
```
That will only copy the values of a into b, not the reference 

### Reshaping Tensors

In [9]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape - while reshaping, it should have the total shape of the original tensor
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [11]:
# flatten - make it 1D 
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# permute
b = torch.rand(2, 3, 4)
print(b)
print(f"Shape of b: {b.shape}")

tensor([[[0.2674, 0.2809, 0.3695, 0.3136],
         [0.6433, 0.7938, 0.2035, 0.3387],
         [0.8352, 0.0640, 0.7563, 0.8070]],

        [[0.1695, 0.3631, 0.2727, 0.4819],
         [0.2553, 0.8255, 0.2505, 0.3655],
         [0.3911, 0.7963, 0.5467, 0.7461]]])
Shape of b: torch.Size([2, 3, 4])


In [19]:
# permute(2, 0, 1) means, in the main tenor = 2 was the 0th, 3 was the 1st and 4 was the 2nd dimension. We are calling
# permute(2, 0, 1) means, make the 2nd dimension as 0th, make the 0th as 1st, and 1 as 2nd
print(b.permute(2, 0, 1))
print(b.permute(2, 0, 1).shape)

tensor([[[0.2674, 0.6433, 0.8352],
         [0.1695, 0.2553, 0.3911]],

        [[0.2809, 0.7938, 0.0640],
         [0.3631, 0.8255, 0.7963]],

        [[0.3695, 0.2035, 0.7563],
         [0.2727, 0.2505, 0.5467]],

        [[0.3136, 0.3387, 0.8070],
         [0.4819, 0.3655, 0.7461]]])
torch.Size([4, 2, 3])


In [20]:
# unsqueeze - adds a new dimension in a given position
c = torch.rand(226, 226, 3) # image size
print(c)
print(c.unsqueeze(0).shape)
print(c.unsqueeze(1).shape)
print(c.unsqueeze(3).shape)

tensor([[[0.4752, 0.7736, 0.5514],
         [0.7380, 0.1013, 0.1877],
         [0.9275, 0.4882, 0.3132],
         ...,
         [0.9075, 0.3585, 0.3922],
         [0.0960, 0.4792, 0.2469],
         [0.1099, 0.1187, 0.8587]],

        [[0.8921, 0.0378, 0.7479],
         [0.9714, 0.8023, 0.3521],
         [0.5325, 0.7352, 0.7677],
         ...,
         [0.6959, 0.1698, 0.0192],
         [0.2382, 0.7762, 0.0481],
         [0.5935, 0.2698, 0.5731]],

        [[0.9666, 0.8334, 0.5114],
         [0.9752, 0.2570, 0.3563],
         [0.4252, 0.5734, 0.0392],
         ...,
         [0.5149, 0.1470, 0.7490],
         [0.5777, 0.0678, 0.0822],
         [0.0644, 0.6846, 0.8988]],

        ...,

        [[0.9705, 0.1575, 0.9484],
         [0.5281, 0.0571, 0.2083],
         [0.7612, 0.6584, 0.7002],
         ...,
         [0.5941, 0.2660, 0.6098],
         [0.4256, 0.7391, 0.5618],
         [0.0651, 1.0000, 0.1969]],

        [[0.4423, 0.5654, 0.9953],
         [0.1836, 0.4441, 0.5404],
         [0.

In [21]:
# squeeze - does exactly opposite of the unsqueeze. Reduces dimensions

### NumPy and PyTorch

In [ ]:
import numpy as np

# convert pytorch tensor to numpy array
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [24]:
b = a.numpy()

In [26]:
type(b)

numpy.ndarray

In [27]:
c = np.array([4, 5, 6])
c

array([4, 5, 6])

In [28]:
d = torch.from_numpy(c)
d

tensor([4, 5, 6])