Improvements will be implemented to the previous example
1. NN Module for automatic weight and bias initialization for complex networks
2. Using loss functions available in PyTorch
3. Will use activation function from nn module
4. No manual gradient descent, should use PyTorch optim classes.

#### **The NN Module**
The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks
efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions,
activation functions and other utilities, enabling us to focus on designing and experimenting with model architectures. 

#### **Key Components of torch.nn**
1. **Modules (Layers):**
    - **nn.Module:** The base class for all neural network modules. Our custom models and layers hodul be subclass of this class
    - **Common Layers:** Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others
2. **Activation Functions:**
    - Funcitons like nn.ReLU, nn.Sigmoid, nn.Tanh etc. introduce non-linearies to the model, allowing it to learn complex patterns
3. **Loss Functions:**
    - Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the model's predictions and the actual targets
4. **Conatiner Modules:**
    - **nn.Sequential**: A sequential container ro stack layers in order.
5. **Regularization and Dropout:**
    - Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve the model's ability to generate new data

#### Code Examples:

1. Binary classification problem
2. One neuron, five features, one output

In [1]:
# create model class
import torch
import torch.nn as nn 

class Model(nn.Module): ## nn.Module is the base class, we need to inherit from this class for creating our model
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1) # nn.Linear is used for the linear weight matrix [simply for wx + b], accepts parameters: (num_of_features, num_of_output)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features) # we are calculating z = wx + b here
        out = self.sigmoid(out)
        
        return out

In [4]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# forward pass
model(features) # nn.Module class is configured as when we well call the instance, it will automatically call the forward() method

tensor([[0.6130],
        [0.7047],
        [0.6532],
        [0.6361],
        [0.6539],
        [0.6242],
        [0.6663],
        [0.5958],
        [0.6093],
        [0.6513]], grad_fn=<SigmoidBackward0>)

In [6]:
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.4287,  0.0505, -0.3826,  0.3565,  0.4283]], requires_grad=True)
Parameter containing:
tensor([0.1043], requires_grad=True)


In [8]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Neural network with hidden layers
- 5 features, 1 hidden layer with 3 neurons, one output
- ReLU in hidden layers

In [9]:
# Create the complex class

class ModelWithLayers(nn.Module):
    def __init__(self, num_of_features):
        super().__init__()
        self.layer1 = nn.Linear(num_of_features, 3) # 3 is the number of output, which will be the hidden layer
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(3, 1) # from 3 neuron to 1 final output
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.layer1(features)
        out = self.relu(out)
        out = self.layer2(out)
        out = self.sigmoid(out)
        
        return out

In [10]:
# create dataset
feats = torch.rand(10, 5)

# create a new model instance
model2 = ModelWithLayers(feats.shape[1])

# run forward pass
model2(feats)

tensor([[0.6045],
        [0.6367],
        [0.5989],
        [0.6208],
        [0.6276],
        [0.5989],
        [0.5989],
        [0.6085],
        [0.6078],
        [0.6266]], grad_fn=<SigmoidBackward0>)

In [12]:
print(model2.layer2.weight)
print(model2.layer2.bias)

Parameter containing:
tensor([[ 0.3655, -0.0372,  0.0106]], requires_grad=True)
Parameter containing:
tensor([0.4008], requires_grad=True)


In [13]:
from torchinfo import summary
summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelWithLayers                          [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Sequential container
We can see, if the number of layer increases, it becomes cumbersome to create the layers and chaining them to the forward pass. Sequential container comes here to salvage us. 

In [14]:
# Sequential Container
class SeqConModel(nn.Module):
    def __init__(self, num_of_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_of_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        
        return out

In [15]:
# create dataset
features = torch.rand(10, 5)

# create model
model = SeqConModel(features.shape[1])

# forward pass
model(features)

tensor([[0.3294],
        [0.3479],
        [0.3599],
        [0.3491],
        [0.3403],
        [0.3495],
        [0.3826],
        [0.3525],
        [0.3690],
        [0.3598]], grad_fn=<SigmoidBackward0>)